name: 'Get next package version'
description: 'Retrieve the last package version from a Nexus directory and increment it to use it in the next package build'
inputs:
  NexusURL: 
    description:  'The URL of the Nexus'
    required: true
  Repository: 
    description:  'The Nexus repository where the packages to browse are located'
    required: true
  RepositoryDirectory: 
    description:  'The Nexus directory where the packages to browse are located'
    required: true
  CommitHash: 
    description:  'The hash of the last commit on the branch. It will be added to the version if provided.'
    required: false
    default: '$null'
outputs:
  nextversion:
    description: "The next version to use"
    value: "${{ steps.getnextversion.outputs.nextversion }}"
runs:
  using: "composite"
  steps:
    - id: getnextversion
      name: Get Next Version
      run: |
          [securestring]$secStringPassword = ConvertTo-SecureString "$env:NEXUS_PASSWORD" -AsPlainText -Force
          [pscredential]$credObject = New-Object System.Management.Automation.PSCredential ("$env:NEXUS_USER", $secStringPassword)

          $Version = ${{ github.action_path }}/GetNextVersion.ps1 -Credential $credObject -NexusURL ${{ inputs.NexusURL }} -Repository ${{ inputs.Repository }} -RepositoryDirectory ${{ inputs.RepositoryDirectory }} -CommitHash ${{ inputs.CommitHash }}

          Write-Output "::set-output name=nextversion::$Version"
      shell: pwsh
